version: 0.2

phases:
  install:
    commands:
      # Install Docker
      - echo Installing Docker...
      - yum update -y
      - yum install -y docker
      # - amazon-linux-extras install docker

      # Install missing dependencies (libcrypt)
      - echo Installing libxcrypt-compat
      - yum install -y libxcrypt-compat
      
      # Start Docker daemon in the background
      - echo Starting Docker daemon...
      - nohup /usr/bin/dockerd > /var/log/dockerd.log 2>&1 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

      # Install Docker Compose
      - echo Installing Docker Compose...
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  
  build:
    commands:
      # Run Docker Compose to build and start services
      - echo Building and starting services using docker-compose...
      - docker-compose up --build -d
  
  # post_build

artifacts:
  files:
    - '**/*'