version: 0.2

phases:
  install:
    commands:
      # Install Docker
      - echo Installing Docker...
      - sudo yum update -y
      - sudo yum install -y docker

      # Install Docker Compose
      - echo Installing Docker Compose...
      - sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

      # Install missing dependencies (libcrypt)
      - echo Installing libxcrypt-compat
      - yum install -y libxcrypt-compat

      # Install AWS CLI
      - echo Installing AWS CLI...
      - yum install -y aws-cli
      
      # # Start Docker daemon in the background
      # - echo Starting Docker daemon...
      # - nohup /usr/bin/dockerd > /var/log/dockerd.log 2>&1 &
      # - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

      # Start Docker daemon
      - sudo service docker start || (sudo dockerd &)

      # Fetch parameters from AWS Parameter Store and export them as environment variables to the images created
      - echo Fetching parameters from AWS Parameter Store...
      - export GOOGLE_OAUTH_CLIENT_ID=$(aws ssm get-parameter --name "/event_management_backend/GOOGLE_OAUTH_CLIENT_ID" --query "Parameter.Value" --output text --region us-east-1)
      - export GOOGLE_OAUTH_CLIENT_SECRET=$(aws ssm get-parameter --name "/event_management_backend/GOOGLE_OAUTH_CLIENT_SECRET" --query "Parameter.Value" --output text --region us-east-1)
      - export DB_NAME=$(aws ssm get-parameter --name "/event_management_backend/DB_NAME" --query "Parameter.Value" --output text --region us-east-1)
      - export DB_USER=$(aws ssm get-parameter --name "/event_management_backend/DB_USER" --query "Parameter.Value" --output text --region us-east-1)
      - export DB_PASSWORD=$(aws ssm get-parameter --name "/event_management_backend/DB_PASSWORD" --query "Parameter.Value" --output text --region us-east-1)
      - export DB_HOST=$(aws ssm get-parameter --name "/event_management_backend/DB_HOST" --query "Parameter.Value" --output text --region us-east-1)
      - export JWT_TOKEN=$(aws ssm get-parameter --name "/event_management_backend/JWT_SECRET" --query "Parameter.Value" --output text --region us-east-1)


artifacts:
  files:
    - '**/*'