version: '3.9'

services:
  postgres_db:
    image: postgres:latest
    container_name: EventManagementDB
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - postgres_db:/var/lib/postgresql/data

  django:
    image: django-docker:em-app
    build: .
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    depends_on:
      - postgres_db
    ports: 
      - "8000:8000"

volumes:
  postgres_db:
    driver: local